// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKO-pKyKOcpfFheil0Z7m3xXI32LgEmQ',
    appId: '1:560048420981:web:0b8985596007738d2b203c',
    messagingSenderId: '560048420981',
    projectId: 'new-buy-cc03a',
    authDomain: 'new-buy-cc03a.firebaseapp.com',
    storageBucket: 'new-buy-cc03a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdH1H4KO4Qq8_1C_MnjC3unRv6jlYIDc',
    appId: '1:560048420981:android:8731e1dc516bec352b203c',
    messagingSenderId: '560048420981',
    projectId: 'new-buy-cc03a',
    storageBucket: 'new-buy-cc03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK1YJRzu__RF-Prw_x-UDJg0_rItSQTbM',
    appId: '1:560048420981:ios:782eb05cb4e6a4fa2b203c',
    messagingSenderId: '560048420981',
    projectId: 'new-buy-cc03a',
    storageBucket: 'new-buy-cc03a.appspot.com',
    iosBundleId: 'com.example.eccommerce',
  );
}
